blank_issues_enabled: true
contact_links:
  - name: Security Disclosures
    url: https://github.com/ARPAHLS/mnemolink/blob/main/SECURITY.md
    about: Please report potential vulnerabilities privately to security@arpacorp.net
  - name: General Inquiries & Proposals
    url: mailto:input@arpacorp.net
    about: Send high-level feedback, partnerships, or domain proposals to ARPA
